# Generated by Django 4.1.4 on 2023-02-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_term_taxonomy_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.comment'),
        ),
    ]
