# Generated by Django 4.1.4 on 2023-02-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_alter_post_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ping_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('published', 'published'), ('Scheduled', 'Scheduled')], default='published', max_length=200),
        ),
    ]
