# Generated by Django 4.1.4 on 2023-02-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='guid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='menu_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pinged',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content_filtered',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_mime_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_parent',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='to_ping',
            field=models.TextField(null=True),
        ),
    ]
