# Generated by Django 4.1.4 on 2023-02-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_post_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='taxonomy',
            new_name='category_name',
        ),
    ]
