# Generated by Django 4.1.4 on 2023-02-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_taxonomy_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
