# Generated by Django 4.1.4 on 2023-02-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_category_name_alter_post_guid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
