# Generated by Django 4.1.4 on 2023-02-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_comment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_image',
            field=models.ImageField(upload_to='images/img'),
        ),
    ]
